In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("../data/raw/Sambhajinagar_Dataset_V2 (1).csv")
df.head()

,system:index,Elevation,LST,Latitude,Longitude,NDBI,NDVI,Population,.geo
0,0,919,43.919170,19.970832,75.438700,0.127207,0.162286,1.562392,"{""type"":""Point"",""coordinates"":[75.438699969521..."
1,1,488,39.060455,19.729093,75.209548,-0.272423,0.570751,1.361367,"{""type"":""Point"",""coordinates"":[75.209547657446..."
2,2,505,40.231127,19.788775,75.225639,0.055877,0.099371,15.386780,"{""type"":""Point"",""coordinates"":[75.225638822972..."
3,3,757,44.884761,19.960297,75.544582,0.121404,0.196037,2.643492,"{""type"":""Point"",""coordinates"":[75.544582071463..."
4,4,586,48.502735,19.867709,75.486062,0.133151,0.165262,31.397209,"{""type"":""Point"",""coordinates"":[75.486061551196..."

In [5]:
df.shape

(9893, 9)

In [6]:
df.columns

Index(['system:index', 'Elevation', 'LST', 'Latitude', 'Longitude', 'NDBI',
       'NDVI', 'Population', '.geo'],
      dtype='str')

In [7]:
df.isnull().sum()

system:index    0
Elevation       0
LST             0
Latitude        0
Longitude       0
NDBI            0
NDVI            0
Population      0
.geo            0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.describe()

,system:index,Elevation,LST,Latitude,Longitude,NDBI,NDVI,Population
count,9893.000000,9893.000000,9893.000000,9893.000000,9893.000000,9893.000000,9893.000000,9893.000000
mean,4996.368948,621.370262,43.463630,19.890409,75.357082,0.029918,0.241080,12.378498
std,2886.809641,85.589970,3.229270,0.085958,0.118384,0.098665,0.115880,29.300305
min,0.000000,483.000000,27.762190,19.723374,75.142142,-0.433368,-0.128937,0.667908
25%,2497.000000,556.000000,41.241152,19.819395,75.255050,-0.021819,0.160441,2.063318
50%,4994.000000,597.000000,43.606422,19.892116,75.356124,0.053535,0.211398,3.155722
75%,7493.000000,691.000000,45.966564,19.963205,75.454214,0.099973,0.296107,7.110859
max,9999.000000,926.000000,51.956644,20.042864,75.586524,0.401310,0.751738,230.774673