In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(
    "../data/raw/Sambhajinagar_UHI_Dataset_V1.csv"
)

df.head()

,system:index,LST,Latitude,Longitude,NDBI,NDVI,.geo
0,0,43.919170,19.970832,75.438700,0.127207,0.162286,"{""type"":""Point"",""coordinates"":[75.438699969521..."
1,1,39.060455,19.729093,75.209548,-0.272423,0.570751,"{""type"":""Point"",""coordinates"":[75.209547657446..."
2,2,40.231127,19.788775,75.225639,0.055877,0.099371,"{""type"":""Point"",""coordinates"":[75.225638822972..."
3,3,44.884761,19.960297,75.544582,0.121404,0.196037,"{""type"":""Point"",""coordinates"":[75.544582071463..."
4,4,48.502735,19.867709,75.486062,0.133151,0.165262,"{""type"":""Point"",""coordinates"":[75.486061551196..."

In [8]:
df.shape

(5000, 5)

In [9]:
df.columns

Index(['LST', 'Latitude', 'Longitude', 'NDBI', 'NDVI'], dtype='str')

In [10]:
df.isnull().sum()

LST          0
Latitude     0
Longitude    0
NDBI         0
NDVI         0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.describe()

               LST     Latitude    Longitude         NDBI         NDVI
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000
mean     43.389135    19.889075    75.357174     0.028941     0.240790
std       3.346183     0.085450     0.119309     0.099037     0.117976
min      27.762190    19.724079    75.142142    -0.383288    -0.128937
25%      41.162965    19.817358    75.254562    -0.023969     0.159963
50%      43.563696    19.889976    75.355773     0.052578     0.211080
75%      45.946056    19.960294    75.456165     0.099394     0.296487
max      51.435396    20.042755    75.585577     0.401310     0.751738