In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(
    "../data/raw/Sambhajinagar_Dataset_V2 (1).csv"
)

df.head()

df.head()

,system:index,Elevation,LST,Latitude,Longitude,NDBI,NDVI,Population,.geo
0,0,919,43.919170,19.970832,75.438700,0.127207,0.162286,1.562392,"{""type"":""Point"",""coordinates"":[75.438699969521..."
1,1,488,39.060455,19.729093,75.209548,-0.272423,0.570751,1.361367,"{""type"":""Point"",""coordinates"":[75.209547657446..."
2,2,505,40.231127,19.788775,75.225639,0.055877,0.099371,15.386780,"{""type"":""Point"",""coordinates"":[75.225638822972..."
3,3,757,44.884761,19.960297,75.544582,0.121404,0.196037,2.643492,"{""type"":""Point"",""coordinates"":[75.544582071463..."
4,4,586,48.502735,19.867709,75.486062,0.133151,0.165262,31.397209,"{""type"":""Point"",""coordinates"":[75.486061551196..."

In [5]:
df.columns

Index(['system:index', 'Elevation', 'LST', 'Latitude', 'Longitude', 'NDBI',
       'NDVI', 'Population', '.geo'],
      dtype='str')

In [6]:
df = df.drop(
    columns=[
        "system:index",
        ".geo"
    ]
)



df.head()

   Elevation        LST   Latitude  Longitude      NDBI      NDVI  Population
0        919  43.919170  19.970832  75.438700  0.127207  0.162286    1.562392
1        488  39.060455  19.729093  75.209548 -0.272423  0.570751    1.361367
2        505  40.231127  19.788775  75.225639  0.055877  0.099371   15.386780
3        757  44.884761  19.960297  75.544582  0.121404  0.196037    2.643492
4        586  48.502735  19.867709  75.486062  0.133151  0.165262   31.397209

In [7]:
df.isnull().sum()

Elevation     0
LST           0
Latitude      0
Longitude     0
NDBI          0
NDVI          0
Population    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [7]:
df = df.drop_duplicates()

df.shape

(5000, 5)

In [9]:
df.dtypes

Elevation       int64
LST           float64
Latitude      float64
Longitude     float64
NDBI          float64
NDVI          float64
Population    float64
dtype: object

In [10]:
df.to_csv(
    "../data/processed/cleaned_uhi_v2.csv",
    index=False
)

print("V2 Cleaned Dataset Saved")

V2 Cleaned Dataset Saved

In [11]:
df.shape

(9893, 7)