In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(
    "../data/processed/cleaned_uhi_v2.csv"
)

df.head()

   Elevation        LST   Latitude  Longitude      NDBI      NDVI  Population
0        919  43.919170  19.970832  75.438700  0.127207  0.162286    1.562392
1        488  39.060455  19.729093  75.209548 -0.272423  0.570751    1.361367
2        505  40.231127  19.788775  75.225639  0.055877  0.099371   15.386780
3        757  44.884761  19.960297  75.544582  0.121404  0.196037    2.643492
4        586  48.502735  19.867709  75.486062  0.133151  0.165262   31.397209

In [4]:
df["Green_Built_Ratio"] = (
    df["NDVI"] /
    (abs(df["NDBI"]) + 0.01)
)

df.head()

,Elevation,LST,Latitude,Longitude,NDBI,NDVI,Population,Green_Built_Ratio
0,919,43.919170,19.970832,75.438700,0.127207,0.162286,1.562392,1.182783
1,488,39.060455,19.729093,75.209548,-0.272423,0.570751,1.361367,2.020910
2,505,40.231127,19.788775,75.225639,0.055877,0.099371,15.386780,1.508423
3,757,44.884761,19.960297,75.544582,0.121404,0.196037,2.643492,1.491866
4,586,48.502735,19.867709,75.486062,0.133151,0.165262,31.397209,1.154459

In [5]:
df["Population_Heat_Index"] = (
    df["Population"] *
    df["NDBI"]
)

In [6]:
df["Elevation_Cooling_Index"] = (
    df["Elevation"] *
    df["NDVI"]
)

In [7]:
df.head()

,Elevation,LST,Latitude,Longitude,NDBI,NDVI,Population,Green_Built_Ratio,Population_Heat_Index,Elevation_Cooling_Index
0,919,43.919170,19.970832,75.438700,0.127207,0.162286,1.562392,1.182783,0.198747,149.140825
1,488,39.060455,19.729093,75.209548,-0.272423,0.570751,1.361367,2.020910,-0.370867,278.526341
2,505,40.231127,19.788775,75.225639,0.055877,0.099371,15.386780,1.508423,0.859774,50.182390
3,757,44.884761,19.960297,75.544582,0.121404,0.196037,2.643492,1.491866,0.320931,148.400233
4,586,48.502735,19.867709,75.486062,0.133151,0.165262,31.397209,1.154459,4.180581,96.843708

In [8]:
df.columns

Index(['Elevation', 'LST', 'Latitude', 'Longitude', 'NDBI', 'NDVI',
       'Population', 'Green_Built_Ratio', 'Population_Heat_Index',
       'Elevation_Cooling_Index'],
      dtype='str')

In [9]:
df[
    [
        "Green_Built_Ratio",
        "Population_Heat_Index",
        "Elevation_Cooling_Index"
    ]
].describe()

       Green_Built_Ratio  Population_Heat_Index  Elevation_Cooling_Index
count        9893.000000            9893.000000              9893.000000
mean            3.984625               0.384507               148.084978
std             4.301744               2.412859                68.702984
min            -2.903357             -32.066005               -71.859134
25%             1.500314              -0.078914               101.100586
50%             2.477985               0.164021               133.644636
75%             4.535040               0.358065               182.240664
max            46.586742              47.796099               505.259259

In [10]:
df.to_csv(
    "../data/processed/featured_uhi_v2.csv",
    index=False
)

print("V2 Feature Engineering Complete")

V2 Feature Engineering Complete

In [11]:
df.shape

(9893, 10)