In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [2]:
df = pd.read_csv(
    "../data/processed/featured_uhi_v2.csv"
)

df.head()

,Elevation,LST,Latitude,Longitude,NDBI,NDVI,Population,Green_Built_Ratio,Population_Heat_Index,Elevation_Cooling_Index
0,919,43.919170,19.970832,75.438700,0.127207,0.162286,1.562392,1.182783,0.198747,149.140825
1,488,39.060455,19.729093,75.209548,-0.272423,0.570751,1.361367,2.020910,-0.370867,278.526341
2,505,40.231127,19.788775,75.225639,0.055877,0.099371,15.386780,1.508423,0.859774,50.182390
3,757,44.884761,19.960297,75.544582,0.121404,0.196037,2.643492,1.491866,0.320931,148.400233
4,586,48.502735,19.867709,75.486062,0.133151,0.165262,31.397209,1.154459,4.180581,96.843708

In [4]:
df["Hotspot"] = (
    df["LST"] >= 45
).astype(int)

df["Hotspot"].value_counts()

Hotspot
0    6354
1    3539
Name: count, dtype: int64

In [13]:
hotspot_percentage = (
    df["Hotspot"].mean()
) * 100

print(
    f"Hotspot Percentage: {hotspot_percentage:.2f}%"
)

Hotspot Percentage: 35.77%

In [5]:
X = df[
    [
        "NDVI",
        "NDBI",
        "Elevation",
        "Population",
        "Latitude",
        "Longitude"
    ]
]

y = df["Hotspot"]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [7]:
rf_classifier = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf_classifier.fit(
    X_train,
    y_train
)

print("Hotspot Model Trained")

Hotspot Model Trained

In [8]:
predictions = rf_classifier.predict(
    X_test
)

predictions[:10]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1])

In [9]:
accuracy = accuracy_score(
    y_test,
    predictions
)

print("Accuracy :", accuracy)

Accuracy : 0.8236483072258717

In [10]:
print(
    classification_report(
        y_test,
        predictions
    )
)

              precision    recall  f1-score   support

           0       0.85      0.88      0.86      1272
           1       0.76      0.73      0.75       707

    accuracy                           0.82      1979
   macro avg       0.81      0.80      0.81      1979
weighted avg       0.82      0.82      0.82      1979

In [11]:
print(
    confusion_matrix(
        y_test,
        predictions
    )
)

[[1113  159]
 [ 190  517]]

In [12]:
feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf_classifier.feature_importances_
})

feature_importance.sort_values(
    by="Importance",
    ascending=False
)

      Feature  Importance
1        NDBI    0.259187
0        NDVI    0.209332
5   Longitude    0.148544
2   Elevation    0.133822
3  Population    0.131297
4    Latitude    0.117818