In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(
    "../data/processed/featured_uhi.csv"
)

df.head()

,LST,Latitude,Longitude,NDBI,NDVI,Green_Built_Ratio,Heat_Exposure_Index
0,43.919170,19.970832,75.438700,0.127207,0.162286,1.182783,5.586821
1,39.060455,19.729093,75.209548,-0.272423,0.570751,2.020910,-10.640952
2,40.231127,19.788775,75.225639,0.055877,0.099371,1.508423,2.248012
3,44.884761,19.960297,75.544582,0.121404,0.196037,1.491866,5.449194
4,48.502735,19.867709,75.486062,0.133151,0.165262,1.154459,6.458205

In [3]:
df["Hotspot"] = np.where(
    df["LST"] >= 45,
    1,
    0
)

df["Hotspot"].value_counts()

Hotspot
0    3225
1    1775
Name: count, dtype: int64

In [4]:
hotspot_percentage = (
    df["Hotspot"].mean()
) * 100

print(
    f"Hotspot Percentage: {hotspot_percentage:.2f}%"
)

Hotspot Percentage: 35.50%

In [5]:
df[
    [
        "LST",
        "NDVI",
        "NDBI",
        "Hotspot"
    ]
].head()

         LST      NDVI      NDBI  Hotspot
0  43.919170  0.162286  0.127207        0
1  39.060455  0.570751 -0.272423        0
2  40.231127  0.099371  0.055877        0
3  44.884761  0.196037  0.121404        0
4  48.502735  0.165262  0.133151        1

In [6]:
df.to_csv(
    "../data/processed/hotspot_dataset.csv",
    index=False
)

print("Hotspot Dataset Saved")

Hotspot Dataset Saved